### ISSUE TITLE
Conditional plugin load

### ISSUE THREAD

**Issue by khataev** [yabeda-rb/yabeda-puma-plugin#28]
Hi! This question is mostly because of educational purposes, so not a real issue. Still, the problem is the following. I was looking in a ways to decrease memory consumption and tried to implement conditional loading of this gem and `yabeda-prometheus` gem based on environment variable. So it look like this:

`Gemfile`
```rb
gem "yabeda-puma-plugin", require: false
gem "yabeda-prometheus", require: false
```

`config/puma.rb`
```rb
if ENV.fetch("ENABLE_YABEDA", false)
  require "yabeda/puma/plugin"
  activate_control_app
  plugin :yabeda
end
```

`routes.rb`
```rb
  if Settings.yabeda.enabled
    require "yabeda/prometheus"
    mount Yabeda::Prometheus::Exporter => "/metrics"
  end
```

but all attempts to require these gems manually lead to this error:

```rb
require "yabeda/puma/plugin.rb"

NoMethodError: undefined method `already_configured?' for Yabeda:Module
from /Users/khataev/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/yabeda-0.11.0/lib/yabeda/railtie.rb:7:in `block in <class:Railtie>'

# or

require "yabeda/prometheus"

NoMethodError: undefined method `already_configured?' for Yabeda:Module
from /Users/khataev/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/yabeda-0.11.0/lib/yabeda/railtie.rb:7:in `block in <class:Railtie>'

# or even

require "yabeda"
NoMethodError: undefined method `already_configured?' for Yabeda:Module
from /Users/khataev/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/yabeda-0.11.0/lib/yabeda/railtie.rb:7:in `block in <class:Railtie>'
```

not sure to understand how everything works when those gems are loaded by bundler, but looks like there is something non-trivial around `yabeda` gem require (on which those two depend). Can you please explain?

**Comment by Envek** [comment]
Hey, sorry for the long wait.

It seems that if you already have Rails application initialized, then `require "yabeda"` [tries to require its railtie](https://github.com/yabeda-rb/yabeda/blob/4f0f687b399c5f28f91074fd39562ed06d0b2c17/lib/yabeda.rb#L11) before declaring essential methods of itself, and that railtie [tries to execute `after_initialize` block](https://github.com/yabeda-rb/yabeda/blob/4f0f687b399c5f28f91074fd39562ed06d0b2c17/lib/yabeda/railtie.rb#L6-L8) in-place.

Probably, moving this railtie require to the end of file should help.
